const mongoose = require("mongoose");

// Categories are NEVER hardcoded in application code. They live here and
// are created either by an admin seed script or dynamically when a user
// (with AI assistance) confirms that no existing category fits their item.
//
// `embedding` is a vector representation of `name + description + aliases`,
// generated by services/ai/embeddingService.js. Because this project runs
// on plain/self-hosted MongoDB (no Atlas Vector Search available), the
// embedding is stored as a plain number array and compared in application
// code with cosine similarity (see services/ai/categoryService.js) rather
// than with a $vectorSearch aggregation stage. If Atlas Vector Search
// becomes available later, this field can be indexed with a vector index
// and the comparison moved into an aggregation pipeline without changing
// the schema.
const CategorySchema = new mongoose.Schema(
    {
        name: { type: String, required: true, trim: true },
        // Normalized form used for fast exact/near-duplicate lookups
        // before falling back to embedding similarity (e.g. "Baby Gear"
        // and "baby-gear" both normalize to "baby gear").
        slug: { type: String, required: true, unique: true, index: true },
        description: { type: String, default: "" },
        aliases: [{ type: String, trim: true }],
        embedding: { type: [Number], default: undefined, select: true },
        embeddingModel: { type: String, default: "" },
        parentCategoryId: { type: mongoose.Schema.Types.ObjectId, ref: "Category", default: null },
        usageCount: { type: Number, default: 0 },
        // "ai" when created via an accepted AI "create new category"
        // suggestion, "admin" when seeded/created by an administrator.
        createdBy: { type: String, enum: ["ai", "admin", "user"], default: "user" },
    },
    { timestamps: true }
);

CategorySchema.index({ name: "text", description: "text", aliases: "text" });
CategorySchema.index({ parentCategoryId: 1 });

const slugify = (name) =>
    name
        .toString()
        .trim()
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)/g, "");

CategorySchema.statics.slugify = slugify;

CategorySchema.pre("validate", function (next) {
    if (this.name && !this.slug) {
        this.slug = slugify(this.name);
    }
    next();
});

module.exports = mongoose.model("Category", CategorySchema);
